#include <iostream>
#include <vector>
#include <unordered_set>
#include <random>
#include <numeric>
#include <chrono>
#include <cmath>
#include <unordered_map>
#include <fstream>
#include <string>
#include <iomanip>
#include <ctime>
#include <sstream>
#include <algorithm>
#include "networkMetrics.h"

using namespace std;

std::random_device rd;
std::mt19937 gen(rd());

bool eventOccurs(double p) {
    std::uniform_real_distribution<> dis(0.0, 1.0);
    return dis(gen) < p;
}

int get_random_integer(int min, int max) {
    std::uniform_int_distribution<> distr(min, max);
    return distr(gen);
}

std::string get_brazil_time() {
    auto now = std::chrono::system_clock::now();
    auto time_t = std::chrono::system_clock::to_time_t(now);
    
    // Brazil is UTC-3 (BRT - Brasí­lia Time)
    // Convert to Brazil time by subtracting 3 hours
    auto brazil_time = std::chrono::system_clock::from_time_t(time_t) - std::chrono::hours(3);
    time_t = std::chrono::system_clock::to_time_t(brazil_time);
    
    std::tm* timeinfo = std::gmtime(&time_t);
    std::stringstream ss;
    ss << std::put_time(timeinfo, "%Y-%m-%d %H:%M:%S BRT");
    return ss.str();
}

std::unordered_map<double, std::vector<double>> p_cache;

double P(double p, int x) {
    if (p == 0.0) {
        return 0.1;
    }
    double denominator = 1.0 - pow(1.0 - p, 10);
    return (p * pow(1.0 - p, x - 1)) / denominator;
}

int get_number_of_steps(double p) {
    if (p_cache.find(p) == p_cache.end()) {
        std::vector<double> weights;
        for (int x = 1; x <= 10; ++x) {
            weights.push_back(P(p, x));
        }
        p_cache[p] = weights;
    }

    std::discrete_distribution<> dist(p_cache[p].begin(), p_cache[p].end());
    return dist(gen) + 1;
}

int random_walk(const std::vector<std::unordered_set<int>>& graph, int start, int number_of_steps) {
    int current_index = start;

    for (int i = 0; i < number_of_steps; i++) {
        const auto& current = graph[current_index];
        if (current.empty()) {
            break;
        }
        
        std::vector<int> neighbors(current.begin(), current.end());
        int set_index = get_random_integer(0, neighbors.size() - 1);
        current_index = neighbors[set_index];
    }

    return current_index;
}

std::vector<std::unordered_set<int>> generate_network(int N, double m, double p, double fp) {
    std::vector<std::unordered_set<int>> graph(10);

    for (int i = 0; i < 10; i++) {
        graph[i].insert((i + 1) % 10);
        if (i > 0) {
            graph[i].insert((i - 1));
        }
    }
    graph[0].insert(9);

    int n_nodes = 10;

    for (int i = 0; i < N; i++) {
        int start = get_random_integer(0, n_nodes - 1);
        int current = start;

        std::vector<int> marked;
        marked.push_back(start);

        // Calculate base number of nodes to mark (integer part of m)
        int base_marked = static_cast<int>(m);
        
        // Mark the base number of nodes
        for (int j = 0; j < base_marked - 1; j++) {
            int number_of_steps = get_number_of_steps(p);
            current = random_walk(graph, current, number_of_steps);
            marked.push_back(current);
        }
        
        // Add one more node with probability equal to the decimal part of m
        double decimal_part = m - base_marked;
        if (eventOccurs(decimal_part)) {
            int number_of_steps = get_number_of_steps(p);
            current = random_walk(graph, current, number_of_steps);
            marked.push_back(current);
        }

        graph.push_back(std::unordered_set<int>());
        
        for (int val : marked) {
            graph[n_nodes].insert(val);
            graph[val].insert(n_nodes);
        }
        
        for (size_t i = 0; i < marked.size(); i++) {
            for (size_t j = i + 1; j < marked.size(); j++) {
                if (marked[i] != marked[j] && eventOccurs(fp)) {
                    graph[marked[i]].insert(marked[j]);
                    graph[marked[j]].insert(marked[i]);
                }
            }
        }

        n_nodes++;
    }

    std::cout << "Network generated successfully\n";

    return graph;
}

void save_network_to_file(const std::vector<std::unordered_set<int>>& graph, const std::string& filename) {
    std::ofstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Error: Could not open file " << filename << " for writing" << std::endl;
        return;
    }
    
    // Write header with network parameters
    file << "# Network generated by C++ algorithm" << std::endl;
    file << "# Format: source target" << std::endl;
    file << "# Each line represents an undirected edge" << std::endl;
    file << std::endl;
    
    // Write edges (avoid duplicates since it's an undirected graph)
    for (size_t i = 0; i < graph.size(); ++i) {
        for (int neighbor : graph[i]) {
            // Only write edge if source < target to avoid duplicates
            if (i < static_cast<size_t>(neighbor)) {
                file << i << " " << neighbor << std::endl;
            }
        }
    }
    
    file.close();
    std::cout << "Network saved to " << filename << std::endl;
}

std::vector<std::unordered_set<int>> generate_network_with_save(int N, double m, double p, double fp, const std::string& filename) {
    auto graph = generate_network(N, m, p, fp);
    
    // Save to file if filename is provided
    if (!filename.empty()) {
        save_network_to_file(graph, filename);
    }
    
    return graph;
}

struct SimulationResult {
    double avgClust;
    double transitivity;
    double avgPathLength;
    double pearsonR;
    double powerLawCoefficient;
    double powerLawCumulativeCoefficient;
    double pearsonRCumulative;
    double maxDegree;
    double constructionTime;
    double pathCalcTime;
    double totalTime;
    size_t numThreads;
};

SimulationResult run_simulation(int N, double p, double m, double friendship_probability, const std::string& executionId = "") {
    SimulationResult result;
    
    auto start_time = std::chrono::high_resolution_clock::now();
    
    std::vector<std::unordered_set<int>> graph;
    
    // Try to load saved graph if checkpointing is enabled
    if (!executionId.empty()) {
        auto fastGraph = loadFastGraphFromFile(executionId);
        if (!fastGraph.empty()) {
            // Convert fastGraph back to unordered_set format
            graph.resize(fastGraph.size());
            for (size_t i = 0; i < fastGraph.size(); ++i) {
                graph[i] = std::unordered_set<int>(fastGraph[i].begin(), fastGraph[i].end());
            }
            std::cout << "Loaded network from checkpoint (same network for resuming distance calculations)" << std::endl;
        } else {
            // Generate new network
            graph = generate_network(N, m, p, friendship_probability);
            // Save it for future resumes
            auto fastGraph = convertToFastGraph(graph);
            saveFastGraphToFile(fastGraph, executionId);
        }
    } else {
        // No checkpointing, just generate
        graph = generate_network(N, m, p, friendship_probability);
    }
    
    auto end_time = std::chrono::high_resolution_clock::now();
    result.constructionTime = std::chrono::duration_cast<std::chrono::milliseconds>(end_time - start_time).count() / 1000.0;
    
    auto metrics = calculateAllMetrics(graph, executionId);
    
    result.avgClust = metrics.clusteringCoefficient;
    result.transitivity = metrics.clusteringCoefficient;
    result.avgPathLength = metrics.avgPathLength;
    result.pearsonR = metrics.pearsonR;
    result.powerLawCoefficient = metrics.powerLawCoefficient;
    result.powerLawCumulativeCoefficient = metrics.powerLawCumulativeCoefficient;
    result.pearsonRCumulative = metrics.pearsonRCumulative;
    result.maxDegree = metrics.maxDegree;
    result.pathCalcTime = metrics.avgPathLengthDuration.count() / 1000.0;
    result.totalTime = result.constructionTime + result.pathCalcTime;
    result.numThreads = metrics.numThreads;
    
    std::cout << "Simulation completed - Clustering: " << result.avgClust 
              << ", Path length: " << result.avgPathLength 
              << ", Construction time: " << result.constructionTime << "s"
              << ", Path calc time: " << result.pathCalcTime << "s"
              << ", Total time: " << result.totalTime << "s"
              << ", Threads: " << metrics.numThreads << "\n";
              
    return result;
}

double calculate_std_dev(const std::vector<double>& values, double mean) {
    double variance = 0.0;
    for (double value : values) {
        double diff = value - mean;
        variance += diff * diff;
    }
    return std::sqrt(variance / values.size());
}

void create_point_sequential(const std::string& filepath, int N, double p, double m, double friendship_probability, int n_simulations, const std::string& executionId = "") {
    std::cout << "Running " << n_simulations << " sequential simulations...\n";
    
    std::vector<SimulationResult> results;
    
    std::ofstream partial_file("partial.txt", std::ios_base::app);
    if (!partial_file.is_open()) {
        std::cerr << "Warning: Could not open partial.txt for writing individual results" << std::endl;
    } else {
        partial_file.seekp(0, std::ios::end);
        if (partial_file.tellp() == 0) {
            partial_file << "Simulation\tN\tp\tm\tfriendship_probability\tavg_clustering\ttransitivity\tavg_path\tr\tslope\tslope_cumulative\tr_cumulative\tmax_degree\tconstruction_time\tpath_calc_time\ttotal_time\tthreads\n";
        }
        partial_file << std::fixed << std::setprecision(4);
    }
    
    for (int i = 0; i < n_simulations; i++) {
        std::cout << get_brazil_time() << " Simulation " << (i+1) << "/" << n_simulations << "...\n";
        // Create unique execution ID for each simulation if provided
        std::string simExecutionId = executionId;
        if (!simExecutionId.empty()) {
            simExecutionId += "_sim" + std::to_string(i + 1);
        }
        SimulationResult result = run_simulation(N, p, m, friendship_probability, simExecutionId);
        results.push_back(result);
        
        if (partial_file.is_open()) {
            partial_file << (i+1) << "\t" 
                         << N << "\t" 
                         << p << "\t" 
                         << m << "\t" 
                         << friendship_probability << "\t"
                         << result.avgClust << "\t"
                         << result.transitivity << "\t"
                         << result.avgPathLength << "\t"
                         << result.pearsonR << "\t"
                         << result.powerLawCoefficient << "\t"
                         << result.powerLawCumulativeCoefficient << "\t"
                         << result.pearsonRCumulative << "\t"
                         << result.maxDegree << "\t"
                         << result.constructionTime << "\t"
                         << result.pathCalcTime << "\t"
                         << result.totalTime << "\t"
                         << result.numThreads << "\n";
        }
    }
    
    if (partial_file.is_open()) {
        partial_file.close();
        std::cout << "Individual simulation results written to partial.txt" << std::endl;
    }
    
    // Calculate averages
    double avg_clust = 0.0, avg_trans = 0.0, avg_path = 0.0, avg_r = 0.0;
    double avg_slope = 0.0, avg_slope_cumulative = 0.0, avg_r_cumulative = 0.0;
    double avg_max_degree = 0.0, avg_construction_time = 0.0;
    double avg_shortest_path_calculation_time = 0.0;
    double avg_total_time = 0.0;
    
    std::vector<double> clust_values, trans_values, path_values, r_values;
    std::vector<double> slope_values, slope_cumulative_values, r_cumulative_values;
    std::vector<double> max_degree_values, construction_time_values, path_calc_time_values;
    std::vector<double> total_time_values;
    
    for (const auto& r : results) {
        avg_clust += r.avgClust;
        avg_trans += r.transitivity;
        avg_path += r.avgPathLength;
        avg_r += r.pearsonR;
        avg_slope += r.powerLawCoefficient;
        avg_slope_cumulative += r.powerLawCumulativeCoefficient;
        avg_r_cumulative += r.pearsonRCumulative;
        avg_max_degree += r.maxDegree;
        avg_construction_time += r.constructionTime;
        avg_shortest_path_calculation_time += r.pathCalcTime;
        avg_total_time += r.totalTime;
        
        clust_values.push_back(r.avgClust);
        trans_values.push_back(r.transitivity);
        path_values.push_back(r.avgPathLength);
        r_values.push_back(r.pearsonR);
        slope_values.push_back(r.powerLawCoefficient);
        slope_cumulative_values.push_back(r.powerLawCumulativeCoefficient);
        r_cumulative_values.push_back(r.pearsonRCumulative);
        max_degree_values.push_back(r.maxDegree);
        construction_time_values.push_back(r.constructionTime);
        path_calc_time_values.push_back(r.pathCalcTime);
        total_time_values.push_back(r.totalTime);
    }
    
    avg_clust /= n_simulations;
    avg_trans /= n_simulations;
    avg_path /= n_simulations;
    avg_r /= n_simulations;
    avg_slope /= n_simulations;
    avg_slope_cumulative /= n_simulations;
    avg_r_cumulative /= n_simulations;
    avg_max_degree /= n_simulations;
    avg_construction_time /= n_simulations;
    avg_shortest_path_calculation_time /= n_simulations;
    avg_total_time /= n_simulations;
    
    double std_clust = calculate_std_dev(clust_values, avg_clust);
    double std_trans = calculate_std_dev(trans_values, avg_trans);
    double std_path = calculate_std_dev(path_values, avg_path);
    double std_r = calculate_std_dev(r_values, avg_r);
    double std_slope = calculate_std_dev(slope_values, avg_slope);
    double std_slope_cumulative = calculate_std_dev(slope_cumulative_values, avg_slope_cumulative);
    double std_r_cumulative = calculate_std_dev(r_cumulative_values, avg_r_cumulative);
    double std_max_degree = calculate_std_dev(max_degree_values, avg_max_degree);
    double std_construction_time = calculate_std_dev(construction_time_values, avg_construction_time);
    double std_shortest_path_calculation_time = calculate_std_dev(path_calc_time_values, avg_shortest_path_calculation_time);
    double std_total_time = calculate_std_dev(total_time_values, avg_total_time);
    
    std::ofstream file(filepath, std::ios_base::app);
    if (file.is_open()) {
        file << std::fixed << std::setprecision(4);
        file << N << "\t" << p << "\t" << m << "\t" << friendship_probability << "\t"
             << avg_clust << " // " << std_clust << "\t"
             << avg_trans << " // " << std_trans << "\t"
             << avg_path << " // " << std_path << "\t"
             << avg_r << " // " << std_r << "\t"
             << avg_slope << " // " << std_slope << "\t"
             << avg_slope_cumulative << " // " << std_slope_cumulative << "\t"
             << avg_r_cumulative << " // " << std_r_cumulative << "\t"
             << avg_max_degree << " // " << std_max_degree << "\t"
             << avg_construction_time << " // " << std_construction_time << "\t"
             << avg_shortest_path_calculation_time << " // " << std_shortest_path_calculation_time << "\t"
             << avg_total_time << " // " << std_total_time << "\n";
        file.close();
        std::cout << "Results written to " << filepath << std::endl;
    } else {
        std::cerr << "Error: Could not open file " << filepath << std::endl;
    }
}

struct LastCompleted {
    int N;
    double p;
    double m;
    double friendship_probability;
    bool valid;
};

LastCompleted get_last_completed_combination(const std::string& output_file) {
    LastCompleted result;
    result.valid = false;
    
    std::ifstream file(output_file);
    if (!file.is_open()) {
        std::cerr << "Debug: Could not open file: " << output_file << std::endl;
        return result;
    }
    
    std::string line;
    std::string last_valid_line;
    
    // Read all lines and find the last non-empty line
    while (std::getline(file, line)) {
        // Skip empty lines and lines starting with #
        if (!line.empty() && line[0] != '#') {
            // Remove leading/trailing whitespace
            size_t first = line.find_first_not_of(" \t");
            if (first != std::string::npos) {
                size_t last = line.find_last_not_of(" \t");
                if (last != std::string::npos && last >= first) {
                    last_valid_line = line.substr(first, last - first + 1);
                }
            }
        }
    }
    
    file.close();
    
    if (last_valid_line.empty()) {
        std::cerr << "Debug: No valid line found in file" << std::endl;
        return result;
    }
    
    std::cerr << "Debug: Last valid line: " << last_valid_line.substr(0, 50) << "..." << std::endl;
    
    // Parse the line - format is tab-separated: N\tp\tm\tfriendship_probability\t...
    std::istringstream iss(last_valid_line);
    std::string token;
    std::vector<std::string> tokens;
    
    while (std::getline(iss, token, '\t')) {
        // Trim whitespace from token
        size_t first = token.find_first_not_of(" \t");
        if (first != std::string::npos) {
            size_t last = token.find_last_not_of(" \t");
            if (last != std::string::npos && last >= first) {
                std::string trimmed = token.substr(first, last - first + 1);
                if (!trimmed.empty()) {
                    tokens.push_back(trimmed);
                }
            }
        }
    }
    
    std::cerr << "Debug: Found " << tokens.size() << " tokens" << std::endl;
    
    if (tokens.size() < 4) {
        std::cerr << "Debug: Not enough tokens (need 4, found " << tokens.size() << ")" << std::endl;
        return result;
    }
    
    try {
        // Extract numeric values (handle cases where token might contain " // std_dev")
        std::string n_str = tokens[0];
        std::string p_str = tokens[1];
        std::string m_str = tokens[2];
        std::string fp_str = tokens[3];
        
        // Remove any trailing " // ..." if present
        size_t pos = n_str.find(" //");
        if (pos != std::string::npos) n_str = n_str.substr(0, pos);
        pos = p_str.find(" //");
        if (pos != std::string::npos) p_str = p_str.substr(0, pos);
        pos = m_str.find(" //");
        if (pos != std::string::npos) m_str = m_str.substr(0, pos);
        pos = fp_str.find(" //");
        if (pos != std::string::npos) fp_str = fp_str.substr(0, pos);
        
        // Trim again after removing " // ..."
        size_t first = n_str.find_first_not_of(" \t");
        if (first != std::string::npos) {
            size_t last = n_str.find_last_not_of(" \t");
            if (last != std::string::npos && last >= first) {
                n_str = n_str.substr(first, last - first + 1);
            }
        }
        first = p_str.find_first_not_of(" \t");
        if (first != std::string::npos) {
            size_t last = p_str.find_last_not_of(" \t");
            if (last != std::string::npos && last >= first) {
                p_str = p_str.substr(first, last - first + 1);
            }
        }
        first = m_str.find_first_not_of(" \t");
        if (first != std::string::npos) {
            size_t last = m_str.find_last_not_of(" \t");
            if (last != std::string::npos && last >= first) {
                m_str = m_str.substr(first, last - first + 1);
            }
        }
        first = fp_str.find_first_not_of(" \t");
        if (first != std::string::npos) {
            size_t last = fp_str.find_last_not_of(" \t");
            if (last != std::string::npos && last >= first) {
                fp_str = fp_str.substr(first, last - first + 1);
            }
        }
        
        std::cerr << "Debug: Parsing N=" << n_str << ", p=" << p_str << ", m=" << m_str << ", fp=" << fp_str << std::endl;
        
        result.N = std::stoi(n_str);
        result.p = std::stod(p_str);
        result.m = std::stod(m_str);
        result.friendship_probability = std::stod(fp_str);
        result.valid = true;
        
        std::cerr << "Debug: Successfully parsed last completed combination" << std::endl;
    } catch (const std::exception& e) {
        // Parsing failed
        std::cerr << "Debug: Parsing exception: " << e.what() << std::endl;
        return result;
    }
    
    return result;
}

bool is_combination_before_or_equal(int curr_N, double curr_m, double curr_p, double curr_fp,
                                     const LastCompleted& last_completed) {
    if (!last_completed.valid) {
        return false;
    }
    
    // Compare in iteration order: N, then m, then fp, then p
    if (curr_N < last_completed.N) {
        return true;
    }
    if (curr_N > last_completed.N) {
        return false;
    }
    
    if (curr_m < last_completed.m) {
        return true;
    }
    if (curr_m > last_completed.m) {
        return false;
    }
    
    if (curr_fp < last_completed.friendship_probability) {
        return true;
    }
    if (curr_fp > last_completed.friendship_probability) {
        return false;
    }
    
    if (curr_p <= last_completed.p) {
        return true;
    }
    return false;
}

struct PathComparisonResult {
    int N;
    double p;
    double m;
    double friendship_probability;
    double exactAveragePathLength;
    double approximateAveragePathLength;
    double error;
    size_t numEdges;
    double exactTime;
    double approximateTime;
    double timeRatio;
};

void print_usage(const char* program_name) {
    std::cout << "Network Simulation Tool\n";
    std::cout << "=======================\n\n";
    std::cout << "Usage: " << program_name << " [OPTIONS]\n\n";
    std::cout << "Required Parameters:\n";
    std::cout << "  -N <number>          Number of nodes to add to the network (e.g., 10000, 200000)\n";
    std::cout << "  -m <number>          Average number of connections per new node (e.g., 2, 4, 5, 6, 8, 10)\n";
    std::cout << "  -p <probability>     Probability parameter for random walk steps (0.0 to 1.0, e.g., 0.1, 0.5, 0.9)\n";
    std::cout << "  -fp <probability>    Friendship probability between marked nodes (0.0 to 1.0, e.g., 0.1, 0.5, 0.9)\n\n";
    std::cout << "Optional Parameters:\n";
    std::cout << "  -n <number>          Number of simulations to run (default: 5)\n";
    std::cout << "  -o <filename>       Output file path (default: output_<N>.txt)\n";
    std::cout << "  -id <execution_id>   Execution ID for checkpoint/resume functionality\n";
    std::cout << "  -h, --help           Show this help message\n\n";
    std::cout << "Examples:\n";
    std::cout << "  " << program_name << " -N 10000 -m 4 -p 0.5 -fp 0.3\n";
    std::cout << "  " << program_name << " -N 200000 -m 6 -p 0.7 -fp 0.5 -n 10 -o results.txt\n";
    std::cout << "  " << program_name << " -N 50000 -m 5 -p 0.3 -fp 0.7 -id my_simulation\n\n";
    std::cout << "Description:\n";
    std::cout << "  This program generates a network using a preferential attachment model\n";
    std::cout << "  and calculates various network metrics including clustering coefficient,\n";
    std::cout << "  average path length, power law coefficients, and more.\n";
}

#ifndef TESTING
int main(int argc, char* argv[]) {
    // Default values
    int N = -1;
    double m = -1.0;
    double p = -1.0;
    double fp = -1.0;
    int n_simulations = 5;
    std::string output_file = "";
    std::string executionId = "";
    
    // Parse command-line arguments
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        
        if (arg == "-h" || arg == "--help") {
            print_usage(argv[0]);
            return 0;
        }
        else if (arg == "-N" && i + 1 < argc) {
            N = std::stoi(argv[++i]);
        }
        else if (arg == "-m" && i + 1 < argc) {
            m = std::stod(argv[++i]);
        }
        else if (arg == "-p" && i + 1 < argc) {
            p = std::stod(argv[++i]);
        }
        else if (arg == "-fp" && i + 1 < argc) {
            fp = std::stod(argv[++i]);
        }
        else if (arg == "-n" && i + 1 < argc) {
            n_simulations = std::stoi(argv[++i]);
        }
        else if (arg == "-o" && i + 1 < argc) {
            output_file = argv[++i];
        }
        else if (arg == "-id" && i + 1 < argc) {
            executionId = argv[++i];
        }
        else {
            std::cerr << "Unknown argument: " << arg << std::endl;
            std::cerr << "Use -h or --help for usage information." << std::endl;
            return 1;
        }
    }
    
    // Validate required parameters
    if (N < 0 || m < 0 || p < 0 || fp < 0) {
        std::cerr << "Error: Missing required parameters.\n\n";
        print_usage(argv[0]);
        return 1;
    }
    
    // Validate parameter ranges
    if (N <= 0) {
        std::cerr << "Error: N must be a positive integer." << std::endl;
        return 1;
    }
    if (m <= 0) {
        std::cerr << "Error: m must be a positive number." << std::endl;
        return 1;
    }
    if (p < 0.0 || p > 1.0) {
        std::cerr << "Error: p must be between 0.0 and 1.0." << std::endl;
        return 1;
    }
    if (fp < 0.0 || fp > 1.0) {
        std::cerr << "Error: fp must be between 0.0 and 1.0." << std::endl;
        return 1;
    }
    if (n_simulations <= 0) {
        std::cerr << "Error: n must be a positive integer." << std::endl;
        return 1;
    }
    
    // Set default output file if not provided
    if (output_file.empty()) {
        std::ostringstream oss;
        oss << "output_" << N << ".txt";
        output_file = oss.str();
    }
    
    // Print configuration
    std::cout << "Network Simulation Configuration:\n";
    std::cout << "  N (nodes): " << N << "\n";
    std::cout << "  m (connections): " << m << "\n";
    std::cout << "  p (walk probability): " << p << "\n";
    std::cout << "  fp (friendship probability): " << fp << "\n";
    std::cout << "  Simulations: " << n_simulations << "\n";
    std::cout << "  Output file: " << output_file << "\n";
    if (!executionId.empty()) {
        std::cout << "  Execution ID: " << executionId << " (checkpointing enabled)\n";
    } else {
        std::cout << "  Execution ID: (not set, checkpointing disabled)\n";
    }
    std::cout << std::endl;
    
    // Check for resume capability
    LastCompleted last_completed = get_last_completed_combination(output_file);
    if (last_completed.valid) {
        if (is_combination_before_or_equal(N, m, p, fp, last_completed)) {
            std::cout << "This combination (N=" << N << ", m=" << m 
                      << ", p=" << p << ", fp=" << fp 
                      << ") appears to be already completed in " << output_file << std::endl;
            std::cout << "Last completed: N=" << last_completed.N 
                      << ", m=" << last_completed.m 
                      << ", p=" << last_completed.p 
                      << ", fp=" << last_completed.friendship_probability << std::endl;
            std::cout << "Skipping to avoid duplicate results." << std::endl;
            return 0;
        }
    }
    
    // Create execution ID if not provided
    if (executionId.empty()) {
        std::ostringstream oss;
        oss << "N" << N << "_m" << m << "_p" << p << "_fp" << fp;
        executionId = oss.str();
    }
    
    // Run the simulation
    std::cout << "Starting simulation..." << std::endl;
    create_point_sequential(output_file, N, p, m, fp, n_simulations, executionId);
    std::cout << "\nSimulation completed successfully!" << std::endl;
    
    return 0;
}
#endif // TESTING
