#!/usr/bin/env python3
"""
Export Edge List Example
=========================
Generates a network and saves it as a standard edge-list file.
The output can be loaded by NetworkX, igraph, Gephi, or any tool
that reads whitespace-separated edge lists.

Usage:
    python examples/export_edge_list.py

Output:
    examples/network_edges.txt
"""

import sys
import os
import random

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'python'))

from python.network_generator import generate_network

# ── Configuration ───────────────────────────────────────────────────────
N = 1000
M = 4
P = 0.5
FP = 0.3
SEED = 42
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), 'network_edges.txt')


def main():
    random.seed(SEED)

    print(f"Generating network (N={N}, m={M}, p={P}, fp={FP}) ...")
    graph = generate_network(N, M, P, FP)

    num_nodes = len(graph)
    num_edges = sum(len(nbrs) for nbrs in graph) // 2

    # Write edge list (source target), one edge per line, source < target
    edges_written = 0
    with open(OUTPUT_FILE, 'w') as f:
        f.write(f"# Edge list generated by real-world-network-algorithm\n")
        f.write(f"# Parameters: N={N}, m={M}, p={P}, fp={FP}, seed={SEED}\n")
        f.write(f"# Nodes: {num_nodes}, Edges: {num_edges}\n")
        f.write(f"# Format: source target (undirected)\n")
        for node in range(num_nodes):
            for neighbor in sorted(graph[node]):
                if node < neighbor:
                    f.write(f"{node} {neighbor}\n")
                    edges_written += 1

    print(f"Saved {edges_written} edges ({num_nodes} nodes) -> {OUTPUT_FILE}")

    # ── Verify the file can be loaded back ──────────────────────────────
    print("\nVerification - loading edge list back:")
    loaded_edges = 0
    loaded_nodes = set()
    with open(OUTPUT_FILE, 'r') as f:
        for line in f:
            if line.startswith('#') or not line.strip():
                continue
            parts = line.strip().split()
            u, v = int(parts[0]), int(parts[1])
            loaded_nodes.add(u)
            loaded_nodes.add(v)
            loaded_edges += 1
    print(f"  Loaded {loaded_edges} edges, {len(loaded_nodes)} unique nodes [OK]")


if __name__ == '__main__':
    main()
